apiVersion: v1
name: conjur-oss
version: 0.2.2
description: A Helm chart for CyberArk Conjur
icon: https://xebialabs-clients-iglusjax.stackpathdns.com/assets/files/logos/CyberArkConjurLogoWhiteBlue.png
keywords:
  - security
  - 'secrets management'
home: https://www.conjur.org
sources:
  - https://github.com/cyberark/conjur-oss-helm-chart
  - https://github.com/cyberark/conjur
maintainers:
  - name: Conjur Maintainers
    email: conj_maintainers@cyberark.com
