#!/bin/bash -e

PG_PORT=5432
SLEEP_TIME=1

if [ "$DATABASE_URL" == "" ]; then
  echo "ERROR: DATABASE_URL not specified!"
  exit 1
fi

if [ "$CONJUR_SEED_FILE" != "" ]; then
  echo "Seed file setting detected. Extracting relevant info..."
  if [ ! -f "$CONJUR_SEED_FILE" ]; then
    echo "ERROR! Cannot find seed file '$CONJUR_SEED_FILE'!"
    exit 1
  fi

  SOLO_PATH="/tmp/solo.json"
  echo "Extracting solo.json and grabbing its values..."
  seedfile-extractor "/etc/chef/solo.json" "$SOLO_PATH"

  echo "Extracting seedfile certificates..."
  hostname=$(jq -r '.conjur.hostname' "$SOLO_PATH")
  seedfile-extractor "/opt/conjur/etc/ssl/ca.pem" "/opt/conjur/etc/ssl/ca/tls.crt"
  seedfile-extractor "/opt/conjur/etc/ssl/$hostname.pem" "/opt/conjur/etc/ssl/cert/tls.crt"
  seedfile-extractor "/opt/conjur/etc/ssl/$hostname.key" "/opt/conjur/etc/ssl/cert/tls.key"

  export CONJUR_ACCOUNT=$(jq -r '.conjur.account' "$SOLO_PATH")

  # fix permissions on the private key
  chmod 600 "/opt/conjur/etc/ssl/cert/tls.key"

  echo "Extracting CONJUR_DATA_KEY..."
  seedfile-extractor "/opt/conjur/etc/possum.key" "/tmp/conjur_data_key"

  # We also don't just want to blindly eval here so we manually extract the value
  data_key_varfile=$(cat /tmp/conjur_data_key)
  rm -rf /tmp/conjur_data_key
  export CONJUR_DATA_KEY="${data_key_varfile#*=}"

  echo "Composing connection string..."

  if [ "$CONJUR_DATABASE_HOSTNAME" == "" ]; then
    echo "ERROR! CONJUR_DATABASE_HOSTNAME env var not defined!"
    exit 1
  fi

  export PGSSLCERT="/opt/conjur/etc/ssl/cert/tls.crt"
  export PGSSLKEY="/opt/conjur/etc/ssl/cert/tls.key"
  export DATABASE_URL="postgres://conjur@$CONJUR_DATABASE_HOSTNAME:$PG_PORT/conjur?sslmode=require"

  echo "Using PGSSLCERT: '$PGSSLCERT'"
  echo "Using PGSSLKEY: '$PGSSLKEY'"
  echo "Using DATABASE_URL: '$DATABASE_URL'"

  echo "Seedfile data extracted!"
fi

# TODO: Wait for PG to be up before continuing

if [ "$DEBUG_CONTAINER" != "" ] && [ "$DEBUG_CONTAINER" != "false" ]; then
  echo "Container debugging activated... Waiting..."
  sleep 999d
fi

exec conjurctl $@
