#!/bin/bash -e

PG_PORT=5432
SLEEP_TIME=1

if [ "$DATABASE_URL" == "" ]; then
  echo "ERROR: DATABASE_URL not specified!"
  exit 1
fi

SOLO_PATH="/tmp/config/config.json"
SSL_KEY="/tmp/tls.key"
if [ -f "$SOLO_PATH" ]; then
  echo "Extracting seedfile certificates..."
  export CONJUR_ACCOUNT=$(jq -r '.conjur.account' "$SOLO_PATH")

  # fix permissions on the private key
  cp "/opt/conjur/etc/ssl/cert/tls.key" "$SSL_KEY"
  chmod 600 "$SSL_KEY"

  # We don't just want to blindly eval here so we manually extract the value
  data_key_varfile=$(cat /tmp/datakey/conjur_data_key)
  export CONJUR_DATA_KEY="${data_key_varfile#*=}"

  echo "Composing connection string..."

  if [ "$CONJUR_DATABASE_HOSTNAME" == "" ]; then
    echo "ERROR! CONJUR_DATABASE_HOSTNAME env var not defined!"
    exit 1
  fi

  export PGSSLCERT="/opt/conjur/etc/ssl/cert/tls.crt"
  export PGSSLKEY="$SSL_KEY"
  export DATABASE_URL="postgres://conjur@$CONJUR_DATABASE_HOSTNAME:$PG_PORT/conjur?sslmode=require"

  echo "Using PGSSLCERT: '$PGSSLCERT'"
  echo "Using PGSSLKEY: '$PGSSLKEY'"
  echo "Using DATABASE_URL: '$DATABASE_URL'"
fi

# TODO: Wait for PG to be up before continuing

if [ "$DEBUG_CONTAINER" != "" ] && [ "$DEBUG_CONTAINER" != "false" ]; then
  echo "Container debugging activated... Waiting..."
  sleep 999d
fi

exec conjurctl $@
