{{- if .Values.ingress.enabled -}}
{{- $fullName := include "conjur-oss.fullname" . -}}
{{- $hosts := .Values.ingress.hosts -}}
{{- $letsencrypt := .Values.ingress.tls.letsencrypt -}}
{{- if $letsencrypt.enabled -}}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ $fullName }}-certificate
  labels:
    app: {{ template "conjur-oss.name" . }}
    chart: {{ template "conjur-oss.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.conjurLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  secretName: {{ $fullName }}-certificate-secret
  issuerRef:
    name: {{ $letsencrypt.issuerRef.name | quote }}
    kind: {{ $letsencrypt.issuerRef.kind | quote }}
  commonName: {{ $hosts | first | quote }}
  dnsNames:
  {{- range $hosts }}
    - {{ . }}
  {{- end }}
  acme:
    config:
    - dns01:
        provider: {{ $letsencrypt.dns01.provider | quote }}
      domains:
      {{- range $hosts }}
        - {{ . }}
      {{- end }}
{{- end }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "conjur-oss.name" . }}
    chart: {{ template "conjur-oss.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.conjurLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{ end -}}
spec:
  backend:
    serviceName: {{ $fullName }}
    servicePort: http
{{- if $letsencrypt.enabled }}
  tls:
    - secretName: {{ $fullName }}-certificate-secret
      hosts:
      {{- range $hosts }}
        - {{ . }}
      {{- end }}
{{- end }}
{{- end }}
