{{ if eq .Values.databaseUrl "" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres
  labels: &AppPostgresServiceLabels
    app: {{ template "conjur-oss.name" . }}-postgres
    chart: {{ template "conjur-oss.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: postgres
{{- with .Values.postgresLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  ports:
  - port: 5432
  selector: *AppPostgresServiceLabels
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres
  labels: &AppPostgresLabels
    app: {{ template "conjur-oss.name" . }}-postgres
    chart: {{ template "conjur-oss.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: postgres
{{- with .Values.postgresLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  replicas: 1
  selector:
    matchLabels: *AppPostgresLabels
  template:
    metadata:
      labels: *AppPostgresLabels
    spec:
      volumes:
{{ if .Values.seedfile }}
      - name: {{ .Release.Name }}-conjur-seedfile-pg-volume
        secret:
          secretName: {{ .Release.Name }}-conjur-seedfile
          # Permission == 0400. JSON spec doesn’t support octal notation.
          defaultMode: 256
{{- else }}
      - name: {{ .Release.Name }}-conjur-ssl-cert-pg-volume
        secret:
          secretName: {{ .Release.Name }}-conjur-ssl-cert
          # Permission == 0400. JSON spec doesn’t support octal notation.
          defaultMode: 256
      - name: {{ .Release.Name }}-conjur-ssl-ca-cert-pg-volume
        secret:
          secretName: {{ .Release.Name }}-conjur-ssl-ca-cert
          # Permission == 0400. JSON spec doesn’t support octal notation.
          defaultMode: 256
{{- end }}
{{ if .Values.postgres.persistentVolume.create }}
      - name: postgres-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-conjur-oss-pvc
{{- end }}

      containers:
      - image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
        imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
        name: postgres
        # TODO: Allow all combos of PV and certs volume mounts
        volumeMounts:
{{ if .Values.seedfile }}
        - name: {{ .Release.Name }}-conjur-seedfile-pg-volume
          mountPath: /opt/conjur/etc/seedfile
          readOnly: true
{{- else }}
        - name: {{ .Release.Name }}-conjur-ssl-cert-pg-volume
          mountPath: /opt/conjur/etc/ssl/cert
          readOnly: true
        - name: {{ .Release.Name }}-conjur-ssl-ca-cert-pg-volume
          mountPath: /opt/conjur/etc/ssl/ca
          readOnly: true
{{- end }}
{{ if .Values.postgres.persistentVolume.create }}
        - mountPath: "/var/lib/postgresql"
          name: postgres-data
{{- end }}
---
{{ end }}
