apiVersion: v1
kind: Service
metadata:
  name: {{ template "conjur-oss.fullname" . }}
  labels: &AppConjurLabels
    app: {{ template "conjur-oss.name" . }}
    chart: {{ template "conjur-oss.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: service
{{- with .Values.conjurLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: *AppConjurLabels
