#!/bin/bash -e

set -o pipefail

if [ $# -lt 3 ]; then
  echo "ERROR: A required argument was not provided!"
  echo "Usage: $0 <archive_path> <source_tar_path> <output_file>"
  exit 1
fi

CONJUR_SEED_FILE="$1"
SOURCE_PATH="$2"
TARGET_PATH="$3"

SOURCE_FILENAME=$(basename $SOURCE_PATH)
TARGET_FILENAME=$(basename $TARGET_PATH)
TARGET_BASEDIR=$(dirname $TARGET_PATH)

if [ "$CONJUR_SEED_FILE" == "" ]; then
  echo "ERROR! CONJUR_SEED_FILE env var not provided!"
  exit 1
fi

if [ ! -f "$CONJUR_SEED_FILE" ]; then
  echo "ERROR: Seedfile not found in path '$CONJUR_SEED_FILE'!"
  echo "Current state of that path:"
  ls -la $(dirname $CONJUR_SEED_FILE)
  exit 1
fi


echo "Removing target file (if exists): $TARGET_PATH ..."
rm -f "$TARGET_PATH"

echo "Creating parent directories: $TARGET_BASEDIR ..."
mkdir -p "$TARGET_BASEDIR"

# The strip-components flag is to avoid extraction into the nested directories
# matching the archive
STRIP_LEVELS=$(echo $SOURCE_PATH | awk -F"/" '{print NF-2}')
echo "Path levels: $STRIP_LEVELS"

echo "Extracting $CONJUR_SEED_FILE:$SOURCE_PATH into $TARGET_PATH ..."
tar -xf "$CONJUR_SEED_FILE" \
    "--strip-components=$STRIP_LEVELS" \
    -C "$TARGET_BASEDIR" \
    "$SOURCE_PATH"

if [ "$TARGET_FILENAME" != "$SOURCE_FILENAME" ]; then
  echo "Renaming source file to match desired one..."
  mv "$TARGET_BASEDIR/$SOURCE_FILENAME" "$TARGET_PATH"
fi

echo "Seedfile '$SOURCE_PATH' extracted to '$TARGET_PATH'!"
