#!/bin/bash -e

echo "Starting configuration of syslog-ng..."

if [ "$CONJUR_SEED_FILE" != "" ]; then
  echo "Seed file setting detected. Extracting relevant info..."
  if [ ! -f "$CONJUR_SEED_FILE" ]; then
    echo "ERROR! Cannot find seed file '$CONJUR_SEED_FILE'!"
    exit 1
  fi

  SOLO_PATH="/tmp/solo.json"
  echo "Extracting solo.json and grabbing its values..."
  seedfile-extractor "/etc/chef/solo.json" "$SOLO_PATH"

  echo "Extracting seedfile certificates..."
  CONJUR_MASTER=$(jq -r '.conjur.master_host' "$SOLO_PATH")
  hostname=$(jq -r '.conjur.hostname' "$SOLO_PATH")
  seedfile-extractor "/opt/conjur/etc/ssl/ca.pem" "/opt/conjur/etc/ssl/ca/tls.crt"
  seedfile-extractor "/opt/conjur/etc/ssl/$hostname.pem" "/opt/conjur/etc/ssl/cert/tls.crt"
  seedfile-extractor "/opt/conjur/etc/ssl/$hostname.key" "/opt/conjur/etc/ssl/cert/tls.key"

  # Fix permissions on the private key
  chmod 600 "/opt/conjur/etc/ssl/cert/tls.key"

  echo "Seedfile data extracted!"
fi

if [ "$CONJUR_MASTER" == "" ]; then
  echo "ERROR: CONJUR_MASTER is not set!"
  exit 1
fi

sed -i "s/\$CONJUR_MASTER/$CONJUR_MASTER/g" /etc/syslog-ng/conf.d/05-conjur-audit.conf

echo "Starting syslog-ng..."
exec /usr/sbin/syslog-ng -d \
                         --persist-file /tmp/syslog-ng.persist \
                         -f /etc/syslog-ng/syslog-ng.conf \
                         "$@"
