#!/bin/bash -e

echo "Starting configuration of syslog-ng..."

SSL_KEY="/tmp/tls.key"

SOLO_PATH="/tmp/config/config.json"
if [ -f "$SOLO_PATH" ]; then
  CONJUR_MASTER=$(jq -r '.conjur.master_host' "$SOLO_PATH")
  hostname=$(jq -r '.conjur.hostname' "$SOLO_PATH")

  # Fix permissions on the private key
  cp "/opt/conjur/etc/ssl/cert/tls.key" "$SSL_KEY"
  chmod 600 "$SSL_KEY"
fi

if [ "$CONJUR_MASTER" == "" ]; then
  echo "ERROR: CONJUR_MASTER is not set!"
  exit 1
fi

sed -i "s/\$CONJUR_MASTER/$CONJUR_MASTER/g" /etc/syslog-ng/conf.d/05-conjur-audit.conf

echo "Starting syslog-ng..."
exec /usr/sbin/syslog-ng -d \
                         --persist-file /tmp/syslog-ng.persist \
                         -f /etc/syslog-ng/syslog-ng.conf \
                         "$@"
